#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

// Represents an array of integers
typedef struct arr_s {
    int *a;
    unsigned int s;
} arr_t;

// Print "Hello, world!"
void *question1(void *arg) {
    printf("Hello, world!\n");
    return NULL;
}

// Print a random value generated by the main thread
void *question2(void *arg) {
    printf("Generated number: %d\n", *(int*)arg);
    return NULL;
}

// Print a random generated by the thread
void *question3(void *arg) {
    int *val = malloc(sizeof(int));
    if (val) {
        *val = 1 + rand() % 100;
        printf("Generated number: %d\n", *val);
        return val;
    } else {
        return printf("Error: cannot allocate memory for val\n"), NULL;
    }
}

// Print average of an array of 5 random values generated by the main thread
void *question4(void *arg) {
    int *array = (int*)arg;
    int avg = 0;
    for (unsigned int i = 0; i < 5; i++) {
        avg += array[i];
    }
    avg /= 5;
    printf("Average: %d\n", avg);
    return NULL;
}

// Print average of an array of n random values generated by the main thread
void *question5(void *arg) {
    arr_t *array = (arr_t*)arg;
    int avg = 0;
    for (unsigned int i = 0; i < array->s; i++) {
        avg += array->a[i];
    }
    avg /= array->s;
    printf("Average: %d\n", avg);
    return NULL;
}

int main() {
    srand(time(NULL));
    pthread_t tid;

    // Question 1
    printf("Question 1:\n");
    pthread_create(&tid, NULL, question1, NULL);
    pthread_join(tid, NULL);

    // Question 2
    printf("\nQuestion 2:\n");
    int val = 1 + rand() % 100;
    printf("Main thread: %d\n", val);
    pthread_create(&tid, NULL, question2, &val);
    pthread_join(tid, NULL);

    // Question 3
    printf("\nQuestion 3:\n");
    int *ret;
    pthread_create(&tid, NULL, question3, NULL);
    pthread_join(tid, (void**)&ret);
    printf("Main thread: %d\n", *ret);
    free(ret);

    // Question 4
    printf("\nQuestion 4:\n");
    arr_t array;
    array.s = 5;
    array.a = malloc(5 * sizeof(int));
    if (array.a) {
        printf("Main thread: array = ");
        for (unsigned int i = 0; i < 5; i++) {
            array.a[i] = 1 + rand() % 100;
            printf("%d ", array.a[i]);
        }
        printf("\n");
        pthread_create(&tid, NULL, question4, array.a);
        pthread_join(tid, NULL);
        free(array.a);
    } else {
        printf("Error: cannot allocate memory for array.a\n");
    }

    // Question 5
    printf("\nQuestion 5:\n");
    arr_t *array2 = malloc(sizeof(arr_t));
    if (array2) {
        array2->s = 10;
        array2->a = malloc(array2->s * sizeof(int));
        if (array2->a) {
            printf("Main thread: array2 = ");
            for (unsigned int i = 0; i < array2->s; i++) {
                array2->a[i] = 1 + rand() % 100;
                printf("%d ", array2->a[i]);
            }
            printf("\n");
            pthread_create(&tid, NULL, question5, array2);
            pthread_join(tid, NULL);
            free(array2->a);
            free(array2);
        } else {
            printf("Error: cannot allocate memory for array2->a\n");
        }
    } else {
        printf("Error: cannot allocate memory for array2\n");
    }

    return 0;
}
